services:
  db:
    image: pgvector/pgvector:pg16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-mavrov}
      PGPORT: 5433
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "5433:5433"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-mavrov} -p 5433"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  ollama:
    image: ollama/ollama:0.5.7
    restart: always
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD-SHELL", "ollama list | grep nomic-embed-text && ollama list | grep llama3.2 && ollama list | grep tinyllama || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 60
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        /bin/ollama serve &
        sleep 5
        ollama pull nomic-embed-text
        ollama pull llama3.2
        ollama pull tinyllama
        wait
    environment:
      - OLLAMA_NUM_PARALLEL=2
      - OLLAMA_MAX_LOADED_MODELS=2
    networks:
      - app-network

  backend:
    image: ${IMAGE_REPO:-maverickde/mavrov.de}-backend:${IMAGE_TAG:-1.2.21}
    restart: always
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5433/${POSTGRES_DB:-mavrov}
      - OLLAMA_URL=http://ollama:11434
      - GENERATION_MODEL=llama3.2
      - FAST_GENERATION_MODEL=tinyllama
      - OTEL_SDK_DISABLED=true
      - CREWAI_TELEMETRY_OPT_OUT=true
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - LINKEDIN_EMAIL=${LINKEDIN_EMAIL:-}
      - LINKEDIN_PASSWORD=${LINKEDIN_PASSWORD:-}
      - LINKEDIN_PUBLIC_ID=${LINKEDIN_PUBLIC_ID:-}
    depends_on:
      db:
        condition: service_healthy
      ollama:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    image: ${IMAGE_REPO:-maverickde/mavrov.de}-frontend:${IMAGE_TAG:-1.2.21}
    restart: always
    expose:
      - "80"
      - "4000"
    environment:
      - NODE_ENV=production
      - NG_ALLOWED_HOSTS=localhost,mavrov.de,127.0.0.1
    depends_on:
      - backend
    networks:
      - app-network

  open-webui:
    image: ghcr.io/open-webui/open-webui:v0.5.10
    container_name: open-webui
    restart: always
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434

    volumes:
      - open-webui_data:/app/backend/data
    depends_on:
      - ollama
    networks:
      - app-network

  proxy:
    image: ${IMAGE_REPO:-maverickde/mavrov.de}-proxy:${IMAGE_TAG:-1.2.21}
    container_name: global_proxy
    restart: always
    ports:
      - "80:80"
      - "10443:443"
    depends_on:
      - frontend
      - backend
      - open-webui
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  ollama_data:
  open-webui_data:
