"""Add image_blob to posts

Revision ID: d45b3e9ce716
Revises: 68db39a6f58e
Create Date: 2026-02-15 14:12:13.693744

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d45b3e9ce716"
down_revision: Union[str, None] = "68db39a6f58e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("image_blob", sa.LargeBinary(), nullable=True))
    op.add_column("posts", sa.Column("image_type", sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "image_type")
    op.drop_column("posts", "image_blob")
    # ### end Alembic commands ###
