"""recruiter inbox interactions

Revision ID: inbox0003
Revises: encrypt0002
Create Date: 2026-09-05 18:33:32.111265

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "inbox0003"
down_revision: str | None = "encrypt0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "interactions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("source_ref", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("company", sa.String(length=200), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_interactions_created_at", "interactions", ["created_at"], unique=False
    )
    op.create_index("ix_interactions_source", "interactions", ["source"], unique=False)
    op.create_index("ix_interactions_status", "interactions", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_interactions_status", table_name="interactions")
    op.drop_index("ix_interactions_source", table_name="interactions")
    op.drop_index("ix_interactions_created_at", table_name="interactions")
    op.drop_table("interactions")
    # ### end Alembic commands ###
