"""job search pipeline opportunities

Revision ID: pipeline0004
Revises: inbox0003
Create Date: 2026-09-05 22:11:55.906821

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "pipeline0004"
down_revision: str | None = "inbox0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Self-adopt guard (same reasoning as inbox0003): the pre-Alembic scenario
    # materializes every current model via create_all before stamping baseline,
    # so post-baseline CREATEs must no-op when the tables already exist.
    if sa.inspect(op.get_bind()).has_table("opportunities"):
        return
    op.create_table(
        "opportunities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company", sa.String(length=200), nullable=False),
        sa.Column("role_title", sa.String(length=200), nullable=False),
        sa.Column("stage", sa.String(length=30), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("recruiter_name", sa.String(length=200), nullable=True),
        sa.Column("recruiter_email", sa.String(length=320), nullable=True),
        sa.Column("link", sa.String(length=1000), nullable=True),
        sa.Column("salary_note", sa.String(length=500), nullable=True),
        sa.Column("next_action", sa.String(length=500), nullable=True),
        sa.Column("next_action_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_opportunities_stage", "opportunities", ["stage"], unique=False)
    op.create_index(
        "ix_opportunities_updated_at", "opportunities", ["updated_at"], unique=False
    )
    op.create_table(
        "opportunity_notes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("opportunity_id", sa.Uuid(), nullable=False),
        sa.Column("interaction_id", sa.Uuid(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["opportunity_id"], ["opportunities.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_opportunity_notes_opportunity",
        "opportunity_notes",
        ["opportunity_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_opportunity_notes_opportunity", table_name="opportunity_notes")
    op.drop_table("opportunity_notes")
    op.drop_index("ix_opportunities_updated_at", table_name="opportunities")
    op.drop_index("ix_opportunities_stage", table_name="opportunities")
    op.drop_table("opportunities")
    # ### end Alembic commands ###
